# Needs 3 containers to run and for simplicity we will use docker-compose
# Requirements are as follows:
# 1. postgresql -- database which will be used by strapi
# 2. strapi -- application which will be used to create and manage content
# 3. nginx -- web server which will be used to serve the strapi application

# containers (services)

services:
  postgres:
    image: postgres:15
    container_name: postgres-container-strapi
    restart: always
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi123
      POSTGRES_DB: strapidb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - strapi-net

  strapi:
    build: .
    container_name: strapi-app
    restart: always
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapidb
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi123

      APP_KEYS: "someRandomKey1,someRandomKey2"
      API_TOKEN_SALT: "someRandomSalt"
      ADMIN_JWT_SECRET: "someAdminJwtSecret"
      JWT_SECRET: "someJwtSecret"
    depends_on:
      - postgres
    networks:
      - strapi-net

  nginx:
    image: nginx:latest
    container_name: nginx-container-strapi
    restart: always
    ports:
      - "80:80"
    depends_on:
      - strapi
    networks:
      - strapi-net
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  strapi-net:
    driver: bridge

volumes:
  postgres-data:
